### PR TITLE
add missing yacc files

### LINKED ISSUE #16: core build is broken
When installing the gazelle command, these errors occur:

    $  go get -u github.com/bazelbuild/rules_go/go/tools/gazelle/gazelle
    # github.com/bazelbuild/buildifier/core
    ../../bazelbuild/buildifier/core/lex.go:142: undefined: yySymType
    ../../bazelbuild/buildifier/core/lex.go:155: undefined: yySymType
    ../../bazelbuild/buildifier/core/lex.go:170: undefined: yySymType
    ../../bazelbuild/buildifier/core/lex.go:433: undefined: _AND
    ../../bazelbuild/buildifier/core/lex.go:434: undefined: _FOR
    ../../bazelbuild/buildifier/core/lex.go:435: undefined: _IF
    ../../bazelbuild/buildifier/core/lex.go:436: undefined: _ELSE
    ../../bazelbuild/buildifier/core/lex.go:437: undefined: _IN
    ../../bazelbuild/buildifier/core/lex.go:438: undefined: _IS
    ../../bazelbuild/buildifier/core/lex.go:439: undefined: _LAMBDA
    ../../bazelbuild/buildifier/core/lex.go:439: too many errors

I imagine a generated file didn't get checked into the repo.

### PR DESCRIPTION
**Pull request by jmhodges**
Created with `go generate`.

Fixes #16

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by jart** [comment]
Is this file really missing though? It's generated by Bazel.

**Comment by jart** [comment]
But I guess there is something to be said for go get support.

**Comment by jmhodges** [comment]
Yeah, rule_go's gazelle is Go-gettable (and I believe that was a goal for their repo), and the README in this repo mention `go install` which is what `go get` uses under the hood. I'm trying bootstrap up a new bazel repo, and `go get` is the first thing I reached for.

**Comment by pmbethe09** [comment]
Also see https://github.com/bazelbuild/buildifier/issues/14

The bazel and Go-way are in conflict here, as bazel is strongly against checking in anything generated, instead doing the generation as part of the BUILD
https://github.com/bazelbuild/buildifier/blob/master/core/BUILD#L4

Since this can be worked around by running:
go get -d github.com/bazelbuild/buildifier/core && go generate github.com/bazelbuild/buildifier/core

As such, we choose not to check this in and stick to the bazel-style.

Also: your change risks staleness.  Suppose someone changes parse.y and forgets to regenerate?  So if we did check this in, a test in the BUILD file is needed to prevent this.

**Comment by pmbethe09** [comment]
I have created https://github.com/bazelbuild/buildifier/pull/19 which does this but also adds the test I was referring to.

**Comment by pmbethe09** [comment]
Fixed in PR 19

**Pull request closed without merging**
