### PR TITLE
buildozer: print arbitrary Exprs with build.FormatString

### LINKED ISSUE #61: Buildozer can't print attrs whose values are more complicated expressions
If I have a rule like
```
test_suite(
    name = "example",
    some_attr = ["foo"] + SOME_CONSTANT,
)
```

and I run `buildozer //:example "print some_attr"`, it prints `(unknown)`. It seems straightforward to instead print `["foo"] + SOME_CONSTANT` using `build.FormatString`. Is there any reason buildozer shouldn't do this?

### PR DESCRIPTION
**Pull request by swolchok**
Fixes #61.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by pmbethe09** [comment]
LGTM, just need to fix CLA

**Comment by pmbethe09** [comment]
Jenkins, test this please.

**Comment by swolchok** [comment]
> CLA

This contribution is being made on behalf of my employer, Facebook.

**Pull request merged**
