### PR TITLE
Update rules_go

### PR DESCRIPTION
**Pull request by vladmos**

### CODE REVIEW

**Comment by pmbethe09** [comment]
Seems like a good idea, but lets do it by tagging rules_go, and then updating the tag here.  WIP

**Comment by vladmos** [comment]
Done.

**Comment by vladmos** [comment]
Ok I'll change to 0.4.0

**Comment by pmbethe09** [comment]
OK, 0.4.0 is live.

**Comment by vladmos** [comment]
Updated.

**Comment by pmbethe09** [comment]
Jenkins, test this please.

**Comment by vladmos** [comment]
I don't know why Jenkins hasn't triggered a build or how I can do it manually, but I've just checked that locally all tests pass.

**Pull request merged**
